# This is a basic workflow to help you get started with Actions

name: Publish in Expo

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: expo/expo-github-action@3.0.0

      - run: npm install
      - run: npm run build --if-present

      - name: login
        run: expo login -u ${{ secrets.EXPO_USER }} -p ${{ secrets.EXPO_PASS }}

      - name: publish
        run: expo publish
